// gate_test.dart — the PHONE half of the cross-language hard-gate contract
// (ADR-3 D4, PHASE-P2 B8, B12).
//
// `test/fixtures/gate_vectors.json` was generated by the TypeScript signer in
// agent-bridge. If Dart and TypeScript ever disagree about the bytes being signed,
// this suite goes red here and the matching suite goes red there.
//
// THE FIXTURE IS TWO FILES IN TWO REPOS. That is the weak point: each suite reads
// its OWN copy, so editing one copy alone would leave the other suite green and the
// two repos silently disagreeing — the exact drift the fixture exists to prevent.
// So both suites also pin the fixture's sha256 to [fixtureSha256]. Change either
// copy and that copy's suite goes red immediately.
//
// Regenerating the vectors legitimately therefore takes three deliberate steps:
// update both copies, and update the pinned hash in both suites. The friction is
// the feature.

import 'dart:convert';
import 'dart:io';

import 'package:crypto/crypto.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:private_agent/bridge/gate.dart';

/// sha256 of `test/fixtures/gate_vectors.json`, and of the byte-identical copy at
/// `agent-bridge/test/fixtures/gate-vectors.json`. Pinned in BOTH repos' suites.
const String fixtureSha256 =
    '2a347ab4751806073699e2e3fcea96903c963ca3c68c06c9b216b677494446f0';

/// The number of vectors the fixture must contain — a truncated file must not pass.
const int fixtureVectorCount = 5;

File _fixtureFile() => File('test/fixtures/gate_vectors.json');

Map<String, dynamic> _fixture() {
  final f = File('test/fixtures/gate_vectors.json');
  expect(f.existsSync(), isTrue,
      reason: 'the shared fixture is missing — it is copied from agent-bridge/test/fixtures');
  return jsonDecode(f.readAsStringSync()) as Map<String, dynamic>;
}

List<Map<String, dynamic>> _vectors() =>
    (_fixture()['vectors'] as List).cast<Map<String, dynamic>>();

void main() {
  group('B15 — the fixture cannot drift between the two repos', () {
    test('the fixture is byte-for-byte the pinned one', () {
      final bytes = _fixtureFile().readAsBytesSync();
      expect(
        sha256.convert(bytes).toString(),
        fixtureSha256,
        reason: 'gate_vectors.json changed. If that was deliberate, update BOTH repos\' '
            'copies and the pinned hash in BOTH suites — otherwise the two repos have '
            'silently diverged and this phone will reject approvals the bridge signs.',
      );
    });

    test('the fixture has not been truncated', () {
      expect(_vectors().length, fixtureVectorCount);
    });
  });

  group('cross-language HMAC contract', () {
    test('every TypeScript-generated vector reproduces in Dart', () {
      final vectors = _vectors();
      expect(vectors, isNotEmpty);
      for (final v in vectors) {
        final p = v['payload'] as Map<String, dynamic>;
        final actual = signPayload(
          deviceSecret: v['device_secret'] as String,
          op: p['op'] as String,
          targetHash: p['target_hash'] as String,
          approvalId: p['approval_id'] as String,
          exp: p['exp'] as int,
        );
        expect(actual, v['signature'],
            reason: 'Dart and TypeScript disagree on vector: ${v['name']}');
      }
    });

    test('the canonical BYTE sequence matches, not just the digest', () {
      // A digest-only check would still pass if someone regenerated the fixture
      // instead of honouring the contract. Pin the bytes.
      for (final v in _vectors()) {
        final p = v['payload'] as Map<String, dynamic>;
        final canonical = canonicalSigningString(
          op: p['op'] as String,
          targetHash: p['target_hash'] as String,
          approvalId: p['approval_id'] as String,
          exp: p['exp'] as int,
        );
        final hex = utf8
            .encode(canonical)
            .map((b) => b.toRadixString(16).padLeft(2, '0'))
            .join();
        expect(hex, v['canonical_utf8_hex'], reason: 'canonical bytes drifted: ${v['name']}');
      }
    });

    test('all four hard-gated ops are covered by the fixture', () {
      final ops = _vectors().map((v) => (v['payload'] as Map)['op']).toSet();
      for (final op in hardGatedOps) {
        expect(ops, contains(op), reason: 'no vector covers $op');
      }
    });
  });

  group('canonical form', () {
    test('is v1-prefixed, NUL-delimited, five fields', () {
      final s = canonicalSigningString(
        op: 'device_double_tap',
        targetHash: 'abc',
        approvalId: 'id1',
        exp: 42,
      );
      expect(s.split('\u0000'), <String>['v1', 'device_double_tap', 'abc', 'id1', '42']);
    });

    test('NUL framing prevents field confusion', () {
      // Without a delimiter op="ab",hash="c" and op="a",hash="bc" would sign the same.
      final a = signPayload(
          deviceSecret: 's', op: 'ab', targetHash: 'c', approvalId: 'd', exp: 1);
      final b = signPayload(
          deviceSecret: 's', op: 'a', targetHash: 'bc', approvalId: 'd', exp: 1);
      expect(a, isNot(b));
    });

    test('every field is bound into the signature', () {
      String sig({String op = 'device_double_tap', String hash = 'h', String id = 'a', int exp = 5}) =>
          signPayload(deviceSecret: 'secret', op: op, targetHash: hash, approvalId: id, exp: exp);
      final base = sig();
      expect(sig(op: 'device_share_file'), isNot(base));
      expect(sig(hash: 'h2'), isNot(base));
      expect(sig(id: 'a2'), isNot(base));
      expect(sig(exp: 6), isNot(base));
      expect(signPayload(
          deviceSecret: 'other', op: 'device_double_tap', targetHash: 'h', approvalId: 'a', exp: 5),
          isNot(base));
    });
  });

  group('requiresHardGate', () {
    test('covers exactly the four phone ops', () {
      expect(requiresHardGate('device_double_tap', {}), isTrue);
      expect(requiresHardGate('device_notification_reply', {}), isTrue);
      expect(requiresHardGate('device_share_file', {}), isTrue);
      // type_text is conditional — only a submit is outbound.
      expect(requiresHardGate('device_type_text', {'submit': true}), isTrue);
      expect(requiresHardGate('device_type_text', {}), isFalse);
      expect(requiresHardGate('device_type_text', {'submit': false}), isFalse);
    });

    test('leaves perception and navigation ungated', () {
      for (final m in [
        'device_tap',
        'device_screenshot',
        'device_get_screen_state',
        'device_open_app',
        'device_swipe',
        'device_press',
      ]) {
        expect(requiresHardGate(m, {}), isFalse, reason: '$m must not need a human');
      }
    });

    test('does NOT cover sms — capcom6 is a separate app the gate cannot reach', () {
      expect(requiresHardGate('sms_send', {}), isFalse);
      expect(requiresHardGate('sms_reply', {}), isFalse);
      expect(hardGatedOps.contains('sms_send'), isFalse);
    });
  });

  group('verifyHardGate', () {
    const secret = 'device-secret-for-tests';
    const now = 1_800_000_000_000;

    Map<String, dynamic> signedParams({
      String op = 'device_double_tap',
      String hash = 'target-hash',
      String id = 'approval-1',
      int? exp,
      String? secretOverride,
      String? opClaim,
    }) {
      final e = exp ?? now + 60_000;
      return <String, dynamic>{
        'approval': <String, dynamic>{
          'approval_id': id,
          'target_hash': hash,
          'exp': e,
          'op': opClaim ?? op,
          'signature': signPayload(
            deviceSecret: secretOverride ?? secret,
            op: op,
            targetHash: hash,
            approvalId: id,
            exp: e,
          ),
        },
      };
    }

    test('a correctly signed, unexpired approval is allowed', () {
      final v = verifyHardGate(
        method: 'device_double_tap',
        params: signedParams(),
        deviceSecret: secret,
        nowMs: now,
      );
      expect(v.allowed, isTrue);
      expect(v.reason, 'allowed');
    });

    test('B8 — no signature at all is refused (the P2 default)', () {
      final v = verifyHardGate(
        method: 'device_double_tap',
        params: const {},
        deviceSecret: secret,
        nowMs: now,
      );
      expect(v.allowed, isFalse);
      expect(v.reason, 'missing_signature');
    });

    test('a tampered signature is refused', () {
      final params = signedParams();
      final appr = params['approval'] as Map<String, dynamic>;
      final sig = appr['signature'] as String;
      appr['signature'] = (sig[0] == '0' ? '1' : '0') + sig.substring(1);
      final v = verifyHardGate(
        method: 'device_double_tap',
        params: params,
        deviceSecret: secret,
        nowMs: now,
      );
      expect(v.reason, 'bad_signature');
    });

    test('a signature made with the WRONG device secret is refused', () {
      final v = verifyHardGate(
        method: 'device_double_tap',
        params: signedParams(secretOverride: 'a-different-secret'),
        deviceSecret: secret,
        nowMs: now,
      );
      expect(v.reason, 'bad_signature');
    });

    test('an expired approval is refused', () {
      final v = verifyHardGate(
        method: 'device_double_tap',
        params: signedParams(exp: now - 1),
        deviceSecret: secret,
        nowMs: now,
      );
      expect(v.reason, 'expired');
    });

    test('an approval for a DIFFERENT op cannot release this one', () {
      // Signed correctly, unexpired — but issued for share_file.
      final params = signedParams(op: 'device_share_file');
      final v = verifyHardGate(
        method: 'device_double_tap',
        params: params,
        deviceSecret: secret,
        nowMs: now,
      );
      expect(v.reason, 'target_mismatch');
    });

    test('an unconfigured device secret refuses rather than skipping the check', () {
      for (final s in <String?>[null, '']) {
        final v = verifyHardGate(
          method: 'device_double_tap',
          params: signedParams(),
          deviceSecret: s,
          nowMs: now,
        );
        expect(v.allowed, isFalse, reason: 'an empty secret must never mean allow');
        expect(v.reason, 'no_device_secret');
      }
    });

    test('a malformed approval block is refused, not crashed on', () {
      for (final bad in <Object?>[
        'not-a-map',
        42,
        <String, dynamic>{'approval_id': 'a'},
        <String, dynamic>{'approval_id': 'a', 'target_hash': 'h', 'signature': 's'},
        <String, dynamic>{'approval_id': 1, 'target_hash': 'h', 'exp': 1, 'signature': 's'},
      ]) {
        final v = verifyHardGate(
          method: 'device_share_file',
          params: <String, dynamic>{'approval': bad},
          deviceSecret: secret,
          nowMs: now,
        );
        expect(v.allowed, isFalse);
        expect(v.reason, 'missing_signature');
      }
    });

    test('an uppercase signature is accepted (hex case is not meaningful)', () {
      final params = signedParams();
      final appr = params['approval'] as Map<String, dynamic>;
      appr['signature'] = (appr['signature'] as String).toUpperCase();
      final v = verifyHardGate(
        method: 'device_double_tap',
        params: params,
        deviceSecret: secret,
        nowMs: now,
      );
      expect(v.allowed, isTrue);
    });
  });

  group('constantTimeEquals', () {
    test('behaves like equality', () {
      expect(constantTimeEquals('abc', 'abc'), isTrue);
      expect(constantTimeEquals('abc', 'abd'), isFalse);
      expect(constantTimeEquals('abc', 'ab'), isFalse);
      expect(constantTimeEquals('', ''), isTrue);
    });
  });
}
